Add support for postgres11
hartmut-co-uk/pg-repack-docker pull request #1
Opened 2020-10-28 00:43 UTC by easel

2020-10-28 09:29 UTC, hartmut-co-uk requested changes
Many thanks, any particular reason not to use latest, which is 1.4.6?
https://github.com/reorg/pg_repack/releases

If possible - could you test if 1.4.6 also works with pg11 / your setup?

2020-10-28 09:29 UTC, hartmut-co-uk commented on scripts/install_pg_repack.sh
> +apt-get remove --auto-remove -y make unzip gcc libssl-dev zlib1g-dev
👍

2020-10-29 13:03 UTC, easel commented
I can definitely test it. The reason I built 1.4.4 was that's the version AWS is using with their postgres11 instances. In an ideal scenario we'd tag 1.4.1 with postgres 10, 1.4.4 with postgres 11 and 1.4.5 / 1.4.6 with their corresponding releases as well.

2020-10-29 18:29 UTC, hartmut-co-uk commented
Agree, good point. As I understand 1.4.6 should be fully backwards compatible though.
Please let me know if 1.4.6 works with pg11 if possible.

Also let me check if I've had integration with docker hub - or also if I might add Github actions + Github package registry support. 🤔

2020-10-29 18:32 UTC, hartmut-co-uk commented
right - I've had it linked with docker hub: https://hub.docker.com/repository/docker/hartmutcouk/pg-repack-docker
so should work with tagging..
I'll try to get this sorted on the WE if I can find time.

Many thanks for the contribution! 👍

2020-10-30 18:45 UTC, easel commented
I'm pretty sure pg_repack itself is compatible, but the issue is you won't always have control of the extension version loaded into the db (with AWS RDS for example). 

My assumption about this container was that it was a convenient way to isolate the "client" from the server for such scenarios, so ideally we'd have a version built for every version of pg_repack along with the most appropriate postgres version.

2020-11-01 09:38 UTC, hartmut-co-uk approved these changes

2020-11-01 09:38 UTC, merged